import { money } from './currency'
import type { DeliveryZone, MenuCategory, MenuItem, Restaurant } from '../types/domain'

export const mockRestaurants: Restaurant[] = [
  {
    id: 'r1',
    name: 'Pizza Hut',
    cuisine: 'Pizza • Fast food',
    imageUrl: '/assets/foodWide.jpg',
    deliveryTimeText: '20–30 mins',
    deliveryTimeMin: 20,
    deliveryTimeMax: 30,
    isOpen: true,
    rating: 4.8,
    description: 'Classic pizza, bowls, and sides for quick city delivery.',
    supportsHalfPortions: false,
  },
  {
    id: 'r2',
    name: 'Jollof Republic',
    cuisine: 'African • Rice bowls',
    imageUrl: '/assets/food.png',
    deliveryTimeText: '25–35 mins',
    deliveryTimeMin: 25,
    deliveryTimeMax: 35,
    isOpen: true,
    rating: 4.7,
    description: 'Jollof rice, grills, and everyday comfort meals.',
    supportsHalfPortions: true,
  },
  {
    id: 'r3',
    name: 'Green Bowl',
    cuisine: 'Healthy • Salads',
    imageUrl: '/assets/cardPic.png',
    deliveryTimeText: '15–25 mins',
    deliveryTimeMin: 15,
    deliveryTimeMax: 25,
    isOpen: false,
    rating: 4.5,
    description: 'Fresh bowls, wraps, and smoothies.',
    supportsHalfPortions: false,
  },
]

export const mockDeliveryZones: DeliveryZone[] = [
  {
    id: 'ikeja',
    label: 'Ikeja',
    description: 'Allen, Opebi, Computer Village and nearby streets',
    fee: money(50000),
  },
  {
    id: 'yaba',
    label: 'Yaba',
    description: 'Sabo, Alagomeji, UNILAG axis',
    fee: money(70000),
  },
  {
    id: 'victoria-island',
    label: 'Victoria Island',
    description: 'Akin Adesola, Oniru, Ahmadu Bello Way',
    fee: money(90000),
  },
  {
    id: 'lekki',
    label: 'Lekki Phase 1',
    description: 'Admiralty, Fola Osibo, Freedom Way',
    fee: money(120000),
  },
]

export const mockMenuCategories: MenuCategory[] = [
  { id: 'c1', restaurantId: 'r1', name: 'Popular', sortOrder: 1 },
  { id: 'c2', restaurantId: 'r1', name: 'Pizza', sortOrder: 2 },
  { id: 'c3', restaurantId: 'r1', name: 'Sides', sortOrder: 3 },
  { id: 'c4', restaurantId: 'r2', name: 'Bowls', sortOrder: 1 },
  { id: 'c5', restaurantId: 'r2', name: 'Grills', sortOrder: 2 },
  { id: 'c6', restaurantId: 'r3', name: 'Salads', sortOrder: 1 },
]

export const mockMenuItems: MenuItem[] = [
  {
    id: 'm1',
    restaurantId: 'r1',
    categoryId: 'c1',
    name: 'Pepperoni Pizza',
    description: 'Thin crust pepperoni pizza with signature sauce.',
    imageUrl: '/assets/foodWide.jpg',
    price: money(500000),
    isAvailable: true,
  },
  {
    id: 'm2',
    restaurantId: 'r1',
    categoryId: 'c1',
    name: 'Supreme Slice Box',
    description: 'Loaded slice box for quick lunch orders.',
    imageUrl: '/assets/cardPic.png',
    price: money(420000),
    isAvailable: true,
  },
  {
    id: 'm3',
    restaurantId: 'r1',
    categoryId: 'c2',
    name: 'Margherita Pizza',
    description: 'Tomato, mozzarella, and fresh basil.',
    imageUrl: '/assets/food.png',
    price: money(450000),
    isAvailable: true,
  },
  {
    id: 'm4',
    restaurantId: 'r1',
    categoryId: 'c2',
    name: 'Volcano Feast',
    description: 'Spicy chicken, peppers, onion, and lava sauce.',
    imageUrl: '/assets/foodWide.jpg',
    price: money(560000),
    isAvailable: true,
  },
  {
    id: 'm5',
    restaurantId: 'r1',
    categoryId: 'c3',
    name: 'Garlic Bread',
    description: 'Baked garlic bread with herb butter.',
    imageUrl: '/assets/cardPic.png',
    price: money(160000),
    isAvailable: true,
  },
  {
    id: 'm6',
    restaurantId: 'r1',
    categoryId: 'c3',
    name: 'Wings Combo',
    description: 'Crispy wings with hot dip.',
    imageUrl: '/assets/food.png',
    price: money(220000),
    isAvailable: false,
  },
  {
    id: 'm7',
    restaurantId: 'r2',
    categoryId: 'c4',
    name: 'Smoky Jollof Bowl',
    description: 'Jollof rice with grilled chicken and slaw.',
    imageUrl: '/assets/food.png',
    price: money(350000),
    isAvailable: true,
  },
  {
    id: 'm8',
    restaurantId: 'r2',
    categoryId: 'c5',
    name: 'Suya Platter',
    description: 'Beef suya skewers with fried plantain.',
    imageUrl: '/assets/foodWide.jpg',
    price: money(400000),
    isAvailable: true,
  },
  {
    id: 'm9',
    restaurantId: 'r3',
    categoryId: 'c6',
    name: 'Caesar Crunch',
    description: 'Romaine, parmesan, croutons, house dressing.',
    imageUrl: '/assets/cardPic.png',
    price: money(300000),
    isAvailable: true,
  },
]
